### PR TITLE
Fix node js exe path on windows

### PR DESCRIPTION
**Pull request by skeetmtp**
append ".exe" to fix file not found error on windows

### CODE REVIEW

**Comment by Slava** [comment]
Is this actually required? It worked fine on my VM

**Comment by skeetmtp** [comment]
Well it didn't worked on my machine. So I opened sublime text console and saw error about the node file not found. I checked where the file was on my machine and the only difference was the missing extension. 
After adding thoses 2 lignes the plugin finaly started. 
This is strange it worked on your VM.

**Comment by Slava** [comment]
Got it, thanks!

**Comment by skeetmtp** [comment]
Nobody has reported plugin not working on Windows ? If you want I ll do more test on differents Windows VM.

**Comment by Slava** [comment]
No, you are the first person reporting.

**Comment by skeetmtp** [comment]
This is just a follow up post to give more informations.
When I encounter the bug on my machine it was on a Windows 7 french with SP1 and Sublime Text 3 build 3065.

I did another try, but this time on a windows 2008 r2 VM ( still Sublime Text 3 (build 3065).
And got same error : 
`
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 157, in on_api_ready
    m.plugin_loaded()
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\Meteor Autocomplete (TernJS)\tern.py", line 629, in plugin_loaded
    os.chmod(node_path, stat.S_IRWXU)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Administrator\\AppData\\Roaming\\Sublime Text 3\\Packages\\Meteor Autocomplete (TernJS)\\dev_bundle\\windows\\node'
`

**Pull request merged**
